name: Lix installation
description: Install Lix package manager

inputs:
  system:
    required: true
    description: Host system tuple

runs:
  using: composite
  steps:
    - name: Install QEMU user‐space emulator
      if: runner.os == 'Linux'
      shell: bash
      run: |
        pkgcache=/var/cache/apt/pkgcache.bin
        if [[ ! -s $pkgcache || $(stat -c %Y $pkgcache) -lt $((EPOCHSECONDS - 86400)) ]]; then
          sudo apt update
        fi
        
        sudo apt install qemu-user-binfmt
    
    - name: Install Lix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        source-url: 'https://install.lix.systems/lix/lix-installer-${{ fromJSON(''{"X64":"x86_64","ARM64":"aarch64"}'')[runner.arch] }}-${{ fromJSON(''{"Linux":"linux","macOS":"darwin","Windows":"windows"}'')[runner.os] }}'
        logger: pretty
        diagnostic-endpoint: ''
        extra-conf: |
          accept-flake-config = true
          experimental-features = nix-command flakes pipe-operator
          substituters = https://cache.kyouma.net https://colmena.cachix.org https://catppuccin.cachix.org https://nix-community.cachix.org https://cache.nixos.org
          trusted-public-keys = cache.kyouma.net:Frjwu4q1rnwE/MnSTmX9yx86GNA/z3p/oElGvucLiZg= colmena.cachix.org-1:7BzpDnjjH8ki2CT3f6GdOk7QAzPOl+1t3LvTLXqYcSg= catppuccin.cachix.org-1:noG/4HkbhJb+lUAdKrph6LaozJvAeEEZj4N732IysmU= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= 
          extra-platforms = ${{ runner.os == 'Linux' && 'riscv64-linux' || '' }}
