name: Lix installation
description: Install Lix package manager

runs:
  using: composite
  steps:
    - name: Cache Nix evaluation cache
      uses: actions/cache@v4
      with:
        key: nix-eval-${{ hashFiles('**/flake.lock') || hashFiles('**/flake.nix') }}
        path: |
          ~/.cache/nix/eval-cache-*

    - name: Install Lix
      shell: sh
      run: |
        curl --proto =https -s -S -f -L https://install.lix.systems/lix \
        | sh -s -- install --no-confirm --enable-flakes --nix-build-user-count "$(nproc || sysctl -n hw.ncpu)" \
        --extra-conf "
        accept-flake-config = true
        experimental-features = nix-command flakes pipe-operator
        trusted-users = root $USER
        "
